spring:
  application: 
    name: microservice-discovery-eureka-ha

server:
  port: 8763

#如果需要将微服务注册到需要认证的eureka server上,只需要将如下配置,配置到被注册的服务中就好
#eureka.client.serviceUrl.defaultZone=http://user:123456@localhost:8762/eureka/

eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456